version: 0.0
os: linux
files:
  - source: /   
    destination: /home/simple/SIMPLE
    
permissions:
  - object: /home/simple/SIMPLE
    pattern: "**"
    owner: simple
    group: simple
    mode: 765
    type:
     - file

  - object: /home/simple/SIMPLE
    pattern: "**"
    owner: simple
    group: simple
    mode: 755
    type:
     - directory

  - object: /home/simple/SIMPLE/upload
    chmod: 775
    type:
     - directory

  - object: /home/simple/SIMPLE/application/logs
    mode: 775
    owner: simple
    type:
     - directory

hooks:
  ApplicationStart:
    - location: simple-start.sh  
