version: 0.0
os: linux
files:
  - source: /   
    destination: /home/simple/SIMPLE

permisions:
  - object: /home/simple/SIMPLE
    owner: simple
    group: simple
    type:
     - files

  - object: /home/simple/SIMPLE
    owner: simple
    group: simple
    type:
     - directory

  - object: /home/simple/SIMPLE/upload
    chmod: 775
    type:
     - directory

  - object: /home/simple/SIMPLE/application/logs
    mode: 775
    owner: simple
    type:
     - directory

hooks:
  ApplicationStart:
    - location: simple-start.sh  
